#ifndef STKQ_POLICY_H
#define STKQ_POLICY_H

namespace stkq {
    enum TYPE {
        INDEX_NSW, INDEX_NSWV2, INDEX_HNSW, INIT_RANDOM, INDEX_NSG, INDEX_GEOGRAPH, INDEX_RTREE, INDEX_RTREE_HNSW,

        REFINE_NN_DESCENT, REFINE_NSG, REFINE_SSG, 

        INIT_NSW, INIT_NSWV2, INIT_HNSW, INIT_GEO_RNG, INIT_GEO_RNG2, INIT_GEO_RNG3, INIT_RTREE,

        SEARCH_ENTRY_RAND, SEARCH_ENTRY_CENTROID, SEARCH_ENTRY_SUB_CENTROID, SEARCH_ENTRY_KDT, SEARCH_ENTRY_KDT_SINGLE, SEARCH_ENTRY_NONE, SEARCH_ENTRY_HASH,
        SEARCH_ENTRY_SPTAG_KDT, SEARCH_ENTRY_SPTAG_BKT, SEARCH_ENTRY_VPT,

        L_SEARCH_ASCEND, L_SEARCH_SET_RECALL, L_SEARCH_ASSIGN,

        ROUTER_GREEDY, ROUTER_IEH, ROUTER_NSW, ROUTER_HNSW, DUAL_ROUTER_HNSW, ROUTER_NGT, ROUTER_BACKTRACK, ROUTER_SPTAG_KDT, ROUTER_SPTAG_BKT, ROUTER_GUIDE, ROUTER_GEOGRAPH, ROUTER_RTREE_HNSW
    };
}

#endif 